- name: Update apt cache and upgrade OS
  hosts: all
  gather_facts: yes
  become: true
  tasks:
    - name: Install Apache on targeted host
      ansible.builtin.apt:
        name: apache2
        state: latest
        update_cache: yes
    
    - name: Start & enable Apache
      ansible.builtin.systemd:
        name: apache2
        enabled: yes
        state: started